### ISSUE TITLE
[BUG] @prizm-ui/components - Краткое описание проблемы

### ISSUE THREAD

**Issue by SergNGZ** [zyfra/Prizm#1315]
### Библиотека

_Выберите нужное отметив галочку [x]_

- [ ] `@prizm-ui/core`
- [+ ] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`
-

### Компонент

prizm-input-layout-date-time
prizm-cron

### Версия

Операционная ситема:

`Windows 10, etc`

Браузер:

`Google Chrome Версия 120.0.6099.225 (Официальная сборка), (64 бит)`

NodeJS:

```
➜ node --version
v14.21.3
```

Dependencies:

```
➜ npm ls @prizm-ui/components

@prizm-ui/components 2.11.0
```

```

### Проект в котором используется Prizm

- КОМ

### Скрин / Видео проблемы

![image](https://github.com/zyfra/Prizm/assets/157575739/1d086564-d7d6-4787-bff9-cc307bb2a8de)

### Описание проблемы
_Есть проблема следующего характера:_

При ручном вводе даты в компоненте prizm-input-layout-date-time возникает ошибка
Error: TypeError: Cannot destructure property 'year' of 'undefined' as it is undefined.
    at PrizmDay.yearAfter (prizm-ui-components.mjs:1177:17)
    at PrizmDay.monthAfter (prizm-ui-components.mjs:1344:21)
    at PrizmDay.dayAfter (prizm-ui-components.mjs:1602:21)
    at PrizmDay.dayLimit (prizm-ui-components.mjs:1615:34)
    at PrizmInputLayoutDateTimeComponent.updateWithCorrectDateAndTime (prizm-ui-components.mjs:20180:25)
    at PrizmInputLayoutDateTimeComponent.onDateValueChange (prizm-ui-components.mjs:20171:14)
    at PrizmInputLayoutDateTimeComponent_Template_input_ngModelChange_5_listener (prizm-ui-components.mjs:20349:1903)

_Шаги воспроизведения_:

В проекте используется настройка { provide: PRIZM_DATE_TIME_VALUE_TRANSFORMER, useClass: DateTimeValueTransformerService }. Для преобразования между Date и Форматом даты призмы.
Если для компонента указать передачу min/max formcontrol, то преобразование не происходит и возникает ошибка, т.к. сохраняется формата Date. В частности такая проблема возникает в компоненте prizm-cron для period.
Предположительно необходимо распространить трансформацию даты на все свойства компонента prizm-input-layout-date-time работающие с датой.

**Comment by ickisIckis** [comment]
связано с #1573
